default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: davidwchristian_development

test:
  <<: *default
  database: davidwchristian_test

production:
  <<: *default
  database: davidwchristian
